# Generated by Django 5.2.5 on 2025-08-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
