# Generated by Django 5.2.5 on 2026-01-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
