# Generated by Django 5.2.5 on 2026-01-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0004_donation_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
