# Generated by Django 5.2.5 on 2026-01-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0005_donation_donor_email_donation_donor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
