# Generated by Django 5.2.5 on 2026-02-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0007_alter_project_created_by_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='profession',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
