# Generated by Django 5.2.5 on 2026-02-01 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0008_volunteer_email_volunteer_name_volunteer_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='contact_info',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='aid.project'),
        ),
    ]
